GUI - Execute tasks
rpa-tomorrow/rpa-tomorrow pull request #209
Opened 2020-12-09 17:11 UTC by viktorfrom

# Proposed changes
* Execute tasks in the play view of GUI instead of just instantiating the them.

# How Has This Been Tested?
Create arbitrary/valid tasks using the GUI and execute them in the play view. 

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

These examples executes the task and displays the message from automation.
- "schedule a meeting at 16 about food" 
- "remind me in 10 seconds to eat" 

**NOTE:** If you create a reminder task you can 't execute it twice, due to threading (same as in the CLI). Further the GUI does not give a prompt about already being booked and just books the meeting anyway. I intend to fix this in an upcoming PR.

# Related issue
Fixes # [136](https://github.com/rpa-tomorrow/substorm-nlp/issues/136)

# Checkboxes
- [ ] I have run the unit tests with `pytest`
- [ ] I formatted the changes with `./scripts/formatter.sh`

2020-12-10 06:31 UTC, Aleman778 approved these changes

2020-12-10 06:31 UTC, Aleman778 commented on src/main/python/design_view.py
> +#     tasks.clear()
Is this code needed?

2020-12-10 07:19 UTC, markhakansson commented
My play view does not display anything at all but I can still execute the tasks?

2020-12-10 09:35 UTC, Aleman778 requested changes
Remove the global array tasks and instead use the builtin model defined in process_model.py instead. All you need to change is before execution convert this model into automation tasks then execute them.

2020-12-10 10:04 UTC, markhakansson commented
Oh sorry thought this issue was finished and removed an unused import such that workflows can run. Maybe I shouldn't have done that.

2020-12-12 17:30 UTC, viktorfrom commented
> Remove the global array tasks and instead use the built-in model defined in process_model.py instead. All you need to change is before execution convert this model into automation tasks then execute them. Then you will always have the correct information even if the user changes something or saves and loads the model.

This has been resolved now.

2020-12-12 17:37 UTC, viktorfrom reviewed
test

2020-12-12 17:44 UTC, markhakansson approved these changes
Tested (except schedule) and it seems to work. Good job.

2020-12-13 10:56 UTC, Aleman778 approved these changes
Looks good! I made some changes to the GUI and execution order of tasks.

2020-12-13 20:17 UTC, merged